defmodule One.Repo.Migrations.AddTicketsAndRepresentativesAndNotes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tickets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :subject, :text
      add :status, :text, null: false, default: "open"
    end

    create table(:representatives, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
    end

    create table(:notes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text

      add :representative_id,
          references(:representatives,
            column: :id,
            name: "notes_representative_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:notes, "notes_representative_id_fkey")

    drop table(:notes)

    drop table(:representatives)

    drop table(:tickets)
  end
end
