defmodule One.Repo.Migrations.AddRepresentativesIsAdmin do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:representatives) do
      add :is_admin, :boolean
    end
  end

  def down do
    alter table(:representatives) do
      remove :is_admin
    end
  end
end
